config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  devise_for :users
  resources :favorites, only: [:update]
  resources :tests_users, only: %i[show update] do
    member do
      get :result
      #post :gist
    end
  end
  resources :tests do 
    resources :comments, only: [:create, :index]
    member do
      post :start
      patch :upvote
      patch :downvote
    end
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end
  resources :categories
  resources :users, only: [:index, :edit, :update] do
    member do
      get :favorite_tests
    end
  end
  root 'tests#index'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  resourcify
  has_many :answers, dependent: :destroy
  belongs_to :test
  validates :body, presence: true

  scope :author, ->(user) { with_role(:author, user).pluck(:id) }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[show edit update destroy]
  before_action :set_test, only: %i[create]

  authorize_resource

  def show
    @answers = @question.answers
    @answer = Answer.new
  end

  def edit; end

  def create
    @test = Test.find(params[:test_id])
    @question = @test.questions.new(question_params)
    user = current_user
    respond_to do |format|
      if @question.save
        format.html { redirect_to question_path(@question), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
    user.add_role :author, @question
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to test_path(@question.test), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', test_path(@question.test) %>

app/views/questions/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<p>
  <strong>Answers:</strong>
</p>

<%= form_with(model: [@question, @answer], local: true) do |f| %>
  <div class="form-group">
    <%= f.label :answer %>
    <%= f.text_area :answer, class: "form-control" %>
  </div>

  <div class="form-group">
    <div class="form-check">
      <%= f.check_box :correct, class: "form-check-input" %>
      <%= f.label :correct, class: "form-check-label"%>
    </div>
  </div>

  <%= f.submit class: "btn btn-primary"%>
<% end %>

<% @answers.each do |answer| %>
  <div class="card my-2">
    <div class="card-body">
      <%= answer.answer %>
      <%= link_to 'Edit', edit_answer_path(answer) %>
      <%= link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }%>
    </div>
  </div>
<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', test_path(@question.test) %>