config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  devise_for :users
  resources :favorites, only: [:update]
  resources :tests_users, only: %i[show update] do
    member do
      get :result
      #post :gist
    end
  end
  resources :tests do 
    resources :comments, only: [:create, :index]
    member do
      post :start
      patch :upvote
      patch :downvote
    end
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end
  resources :categories
  resources :users, only: [:index, :edit, :update] do
    member do
      get :favorite_tests
    end
  end
  root 'tests#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  acts_as_voter
  
  after_create :assign_default_role
  after_create :assign_default_admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :tests_users
  has_many :tests, through: :tests_users
  has_many :favorites, dependent: :destroy
  has_many :favorite_tests, through: :favorites, source: :test

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def tests_user(test)
    tests_users.order(id: :desc).find_by(test_id: test.id)
  end


  def assign_default_role
    self.add_role(:reader) if self.roles.blank?
  end

  def assign_default_admin
    self.add_role(:admin) if User.all.count == 1
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[edit update favorite_tests]
  
  authorize_resource

  def index
    @users = User.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def favorite_tests
    @tests = @user.favorite_tests
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(role_ids: [])
  end
end

app/views/users/edit.html.erb
<div class="container">
  <%= form_with(model: @user) do |f| %>
    <%= f.collection_check_boxes :role_ids, Role.all, :id, :name %>
    <%= @user.errors[(:roles)] %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/favorite_tests.html.erb
<h1>Tests</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Level</th>
      <th>Author</th>
      <th>Upvote</th>
      <th>Cached score</th>
      <th>Downvote</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tests.each do |test| %>
      <tr>
        <td><%= test.title %></td>
        <td><%= test.category.title %></td>
        <td><%= test.level %></td>
        <td><%= User.with_role(:author, test).pluck(:email) %></td>
        <td><%= render "tests/upvote_link", test: test %></td>
        <td><%= render "tests/votes_score", test: test %></td>
        <td><%= render "tests/downvote_link", test: test %></td>
        <td><%= button_to 'Start', start_test_path(test), class: 'btn btn-primary' %>
        <td><%= link_to 'Comments', test_comments_path(test), class: 'btn btn-primary' %>
        <td><%= link_to favorite_helper(test, current_user), favorites_update_path(test: test), remote: true, data: { test_id: test.id }, class: "test-#{test.id} favorite" %>
        
        <%# if user && user.has_role?(:reader)%>
        <% if user_signed_in? %>
          <td><%= link_to 'Show', test %></td>
          <td><%= link_to 'Edit', edit_test_path(test) %></td>
          <td><%= link_to 'Destroy', test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test', new_test_path, class: "btn btn-primary" %>

app/views/users/index.html.erb
<h1>Users</h1>


<table class="table">
  <thead>
    <tr>
      <th>email</th>
      <th>roles</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  
  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.roles.pluck(:name) %> 
    <td><%= link_to 'Edit', edit_user_path(user) %> 
  </tr>
<% end %>