config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  devise_for :users
  resources :favorites, only: [:update]
  resources :tests_users, only: %i[show update] do
    member do
      get :result
      #post :gist
    end
  end
  resources :tests do 
    resources :comments, only: [:create, :index]
    member do
      post :start
      patch :upvote
      patch :downvote
    end
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end
  resources :categories
  resources :users, only: [:index, :edit, :update] do
    member do
      get :favorite_tests
    end
  end
  root 'tests#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">Top navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Tests', tests_path ,class: "nav-link"%>
          </li>
          <% if can? :read, Category %>
            <li class="nav-item">
              <%= link_to 'Categories', categories_path ,class: "nav-link"%>
            </li>
          <% end %>
          <% if can? :read, User %>
            <li class="nav-item">
              <%= link_to 'Users', users_path ,class: "nav-link"%>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2" type="submit">Search</button>
        </form>
        <% if current_user.present? %>
        <li class="nav-item dropdown show">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= current_user.email %></a>
          <div class="dropdown-menu" aria-labelledby="dropdown03">
            <a class="dropdown-item" href="#">Action</a>
            <%= link_to 'Favorites tests', favorite_tests_user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary mx-2" %>
          <%= link_to 'Sign in', new_user_session_path ,class: "btn btn-primary mx-2"%>
        <% end %>
      </div>
    </nav>